export const URL_MAP: Record<string, string> = {
  youtube: 'https://youtube.com',
  'you tube': 'https://youtube.com',
  google: 'https://google.com',
  github: 'https://github.com',
  twitter: 'https://twitter.com',
  x: 'https://x.com',
  facebook: 'https://facebook.com',
  instagram: 'https://instagram.com',
  reddit: 'https://reddit.com',
  linkedin: 'https://linkedin.com',
  netflix: 'https://netflix.com',
  gmail: 'https://mail.google.com',
  maps: 'https://maps.google.com',
  'google maps': 'https://maps.google.com',
  docs: 'https://docs.google.com',
  'google docs': 'https://docs.google.com',
  drive: 'https://drive.google.com',
  'google drive': 'https://drive.google.com',
  spotify: 'https://spotify.com',
  discord: 'https://discord.com',
  whatsapp: 'https://web.whatsapp.com',
  telegram: 'https://web.telegram.org',
  amazon: 'https://amazon.com',
  ebay: 'https://ebay.com',
  stackoverflow: 'https://stackoverflow.com',
  'stack overflow': 'https://stackoverflow.com'
}
