#!/bin/bash

echo "🚀 JARVIS WhatsApp Bot - Render Deployment"
echo "==========================================="

echo ""
echo "📋 Manual Deployment Steps:"
echo "==========================="
echo ""
echo "1. 🌐 Go to https://render.com"
echo "2. 🔐 Sign up/Login with GitHub"
echo "3. ➕ Click 'New +'"
echo "4. 🌐 Choose 'Web Service'"
echo "5. 🔗 Connect your GitHub account"
echo "6. 📁 Select your jarvis repository"
echo "7. 📂 Choose the whatsapp-bot folder"
echo ""
echo "⚙️  Configuration:"
echo "=================="
echo "- Name: jarvis-whatsapp-bot"
echo "- Environment: Node"
echo "- Build Command: npm install"
echo "- Start Command: npm start"
echo "- Plan: Free"
echo ""
echo "🔑 Environment Variables:"
echo "========================="
echo "VITE_GEMINI_API_KEY=your_gemini_api_key"
echo "VITE_SUPABASE_URL=your_supabase_url"
echo "VITE_SUPABASE_ANON_KEY=your_supabase_anon_key"
echo ""
echo "✅ Click 'Create Web Service'"
echo ""
echo "🎉 Your bot will be available at:"
echo "   https://jarvis-whatsapp-bot.onrender.com"
echo "📊 Health check: /health"
echo ""
echo "📱 Don't forget to:"
echo "   1. Set environment variables in Render dashboard"
echo "   2. Check logs for QR code on first run"
echo "   3. Scan QR code with your WhatsApp"
echo ""
echo "🎯 Render Advantages:"
echo "====================="
echo "✅ 750 free hours/month (vs 500 on Railway)"
echo "✅ Custom domains"
echo "✅ Better free tier"
echo "✅ Easy deployment"
echo "✅ Persistent connections"
echo ""
echo "🚀 Ready to deploy! Follow the steps above."
